export type {
  SessionState,
  TerminalState,
} from "./session.js";
export {
  isValidTransition,
  isTerminalState,
  MAX_REFINEMENT_ROUNDS,
  MAX_VERIFICATION_ATTEMPTS,
} from "./session.js";

export type {
  CostInfo,
  GuardLimits,
} from "./cost.js";
export {
  CostInfoSchema,
  GuardLimitsSchema,
  DEFAULT_GUARD_LIMITS,
} from "./cost.js";

export type {
  DomMeta,
  AnnotationAnchor,
  AnnotationStatus,
  AnnotationReply,
  AnnotationThread,
} from "./annotations.js";
export {
  DomMetaSchema,
  AnnotationAnchorSchema,
  AnnotationStatusSchema,
  AnnotationReplySchema,
  AnnotationThreadSchema,
} from "./annotations.js";

export type {
  QuestionOption,
  AnswerableBy,
} from "./questions.js";
export {
  QuestionOptionSchema,
  AnswerableBySchema,
} from "./questions.js";

export type {
  LLMProviderId,
  LLMProviderDefinition,
} from "./providers.js";
export {
  LLM_PROVIDERS,
  getProviderDefinition,
} from "./providers.js";

export type {
  SessionCreatedEvent,
  StatusEvent,
  CloneProgressEvent,
  PhaseEvent,
  AgentEventWrapper,
  PlanReadyEvent,
  VerificationFailedEvent,
  CompleteEvent,
  ErrorEvent,
  PreviewStartingEvent,
  PreviewReadyEvent,
  PreviewErrorEvent,
  PreviewStoppedEvent,
  PreviewAppsEvent,
  RoomReadyEvent,
  ParticipantJoinedEvent,
  ParticipantLeftEvent,
  HumanMessageEvent,
  AgentRequestEvent,
  AgentRequestQueuedEvent,
  AgentRunStartedEvent,
  ApprovalRequestedEvent,
  AgentRunCompletedEvent,
  AgentRunFailedEvent,
  AgentResponseEvent,
  PlanRevisionFrozenEvent,
  AnnotationCreatedEvent,
  AnnotationRepliedEvent,
  AnnotationWithdrawnEvent,
  ConsolidationStartedEvent,
  BriefDispatchedEvent,
  AnnotationsConsumedEvent,
  QuestionRaisedEvent,
  QuestionAssignedEvent,
  QuestionAnsweredEvent,
  DOToCLIEvent,
  ApproveMessage,
  AbortMessage,
  RefinePlanMessage,
  PreviewStartMessage,
  PreviewStopMessage,
  StopSessionMessage,
  HumanChatMessage,
  AgentRequestMessage,
  AnnotationCreateMessage,
  AnnotationReplyMessage,
  AnnotationWithdrawMessage,
  ApproveRunMessage,
  RefineRunMessage,
  AbortRunMessage,
  QuestionAssignMessage,
  QuestionAnswerMessage,
  CLIToDOMessage,
} from "./messages-cli.js";
export {
  SessionCreatedEventSchema,
  StatusEventSchema,
  CloneProgressEventSchema,
  PhaseEventSchema,
  AgentEventWrapperSchema,
  PlanReadyEventSchema,
  VerificationFailedEventSchema,
  CompleteEventSchema,
  ErrorEventSchema,
  PreviewStartingEventSchema,
  PreviewReadyEventSchema,
  PreviewErrorEventSchema,
  PreviewStoppedEventSchema,
  PreviewAppsEventSchema,
  RoomReadyEventSchema,
  ParticipantJoinedEventSchema,
  ParticipantLeftEventSchema,
  HumanMessageEventSchema,
  AgentRequestEventSchema,
  AgentRequestQueuedEventSchema,
  AgentRunStartedEventSchema,
  ApprovalRequestedEventSchema,
  AgentRunCompletedEventSchema,
  AgentRunFailedEventSchema,
  AgentResponseEventSchema,
  PlanRevisionFrozenEventSchema,
  AnnotationCreatedEventSchema,
  AnnotationRepliedEventSchema,
  AnnotationWithdrawnEventSchema,
  ConsolidationStartedEventSchema,
  BriefDispatchedEventSchema,
  AnnotationsConsumedEventSchema,
  QuestionRaisedEventSchema,
  QuestionAssignedEventSchema,
  QuestionAnsweredEventSchema,
  DOToCLIEventSchema,
  PersistedDOToCLIEventSchema,
  ApproveMessageSchema,
  AbortMessageSchema,
  RefinePlanMessageSchema,
  PreviewStartMessageSchema,
  PreviewStopMessageSchema,
  StopSessionMessageSchema,
  HumanChatMessageSchema,
  AgentRequestMessageSchema,
  AnnotationCreateMessageSchema,
  AnnotationReplyMessageSchema,
  AnnotationWithdrawMessageSchema,
  ApproveRunMessageSchema,
  RefineRunMessageSchema,
  AbortRunMessageSchema,
  QuestionAssignMessageSchema,
  QuestionAnswerMessageSchema,
  CLIToDOMessageSchema,
} from "./messages-cli.js";

export type {
  InitMessage,
  AgentTurnMessage,
  PlanMessage,
  ExecuteMessage,
  RefinePlanSandboxMessage,
  CreatePRMessage,
  CredentialResponseMessage,
  CreatePRResponseMessage,
  PreviewStartSandboxMessage,
  PreviewStopSandboxMessage,
  ConsolidationAnnotation,
  ConsolidateAnnotationsMessage,
  AskQuestionResponse,
  AskQuestionCancelled,
  DOToSandboxMessage,
  SandboxAgentEvent,
  SandboxCloneStarted,
  SandboxCloneComplete,
  SandboxStatus,
  SandboxCloneProgress,
  SandboxPlanReady,
  AgentTurnComplete,
  CreatePRRequest,
  ExecutionComplete,
  SandboxVerificationStarted,
  SandboxVerificationRetrying,
  SandboxVerificationFailed,
  CredentialRequest,
  BranchPushed,
  PRCreated,
  SandboxError,
  SandboxPreviewStarting,
  SandboxPreviewReady,
  SandboxPreviewError,
  SandboxPreviewStopped,
  SandboxPreviewApps,
  ConsolidationComplete,
  ConsolidationFailed,
  AskQuestionRequest,
  SandboxToDOMessage,
} from "./messages-sandbox.js";
export {
  InitMessageSchema,
  AgentTurnMessageSchema,
  PlanMessageSchema,
  ExecuteMessageSchema,
  RefinePlanSandboxMessageSchema,
  CreatePRMessageSchema,
  CredentialResponseMessageSchema,
  CreatePRResponseMessageSchema,
  PreviewStartSandboxMessageSchema,
  PreviewStopSandboxMessageSchema,
  ConsolidationAnnotationSchema,
  ConsolidateAnnotationsMessageSchema,
  AskQuestionResponseSchema,
  AskQuestionCancelledSchema,
  DOToSandboxMessageSchema,
  SandboxAgentEventSchema,
  SandboxCloneStartedSchema,
  SandboxCloneCompleteSchema,
  SandboxStatusSchema,
  SandboxCloneProgressSchema,
  SandboxPlanReadySchema,
  AgentTurnCompleteSchema,
  CreatePRRequestSchema,
  ExecutionCompleteSchema,
  SandboxVerificationStartedSchema,
  SandboxVerificationRetryingSchema,
  SandboxVerificationFailedSchema,
  CredentialRequestSchema,
  BranchPushedSchema,
  PRCreatedSchema,
  SandboxErrorSchema,
  SandboxPreviewStartingSchema,
  SandboxPreviewReadySchema,
  SandboxPreviewErrorSchema,
  SandboxPreviewStoppedSchema,
  SandboxPreviewAppsSchema,
  ConsolidationCompleteSchema,
  ConsolidationFailedSchema,
  AskQuestionRequestSchema,
  SandboxToDOMessageSchema,
} from "./messages-sandbox.js";

export type {
  PreviewApp,
  PreviewFramework,
} from "./preview.js";
export {
  PreviewAppSchema,
  PreviewFrameworkSchema,
} from "./preview.js";

export type {
  AuthRole,
  AuthAction,
} from "./auth.js";
export {
  AuthRoleSchema,
  AuthActionSchema,
  can,
} from "./auth.js";

export type {
  Config,
  ConfigDefaults,
} from "./config.js";
export { DEFAULT_CONFIG } from "./config.js";

export type {
  RoomState,
  SandboxState,
  AgentRunState,
  ParticipantIdentity,
  SessionSummary,
  CreateSessionRequest,
  CreateSessionResponse,
  ListSessionsResponse,
  GetSessionResponse,
} from "./room.js";
export {
  RoomStateSchema,
  SandboxStateSchema,
  AgentRunStateSchema,
  ParticipantIdentitySchema,
  SessionSummarySchema,
  CreateSessionRequestSchema,
  CreateSessionResponseSchema,
  ListSessionsResponseSchema,
  GetSessionResponseSchema,
} from "./room.js";

export type {
  PiAgentEvent,
  PiToolExecutionStart,
  PiToolExecutionUpdate,
  PiToolExecutionEnd,
  PiMessageStart,
  PiMessageUpdate,
  PiMessageEnd,
  PiTurnStart,
  PiTurnEnd,
  PiAgentStart,
  PiAgentEnd,
  PiUnknownEvent,
} from "./pi-events.js";
export {
  PiAgentEventSchema,
  PiToolExecutionStartSchema,
  PiToolExecutionUpdateSchema,
  PiToolExecutionEndSchema,
  PiMessageStartSchema,
  PiMessageUpdateSchema,
  PiMessageEndSchema,
  PiTurnStartSchema,
  PiTurnEndSchema,
  PiAgentStartSchema,
  PiAgentEndSchema,
  PiUnknownEventSchema,
} from "./pi-events.js";

export type {
  ChatMessageRole,
  ChatMessageMeta,
  ChatMessage,
  ActivityEntryStatus,
  ActivityEntry,
  PreviewStatus,
  PreviewState,
  PlanRevisionState,
  QuestionAnswer,
  QuestionViewModel,
  ParticipantIdentity as ProjectionParticipantIdentity,
} from "./projection-types.js";

export type {
  ProjectionContext,
  SessionSnapshot,
  ProjectedSessionView,
} from "./projections.js";
export {
  emptyPreviewState,
  emptySessionSnapshot,
  applyToSessionSnapshot,
  inferPhase,
  inferPlanApproved,
  reducePreviewState,
  reducePlanRevision,
  reduceParticipants,
  reduceAnnotations,
  parseRaisedAt,
  reduceQuestions,
  mapEventToChat,
  mapEventToActivity,
  projectEvent,
  projectEvents,
} from "./projections.js";

export type { Boundary, ValidationDrop } from "./validation.js";
export {
  parseInbound,
  setValidationDropSink,
  tracerValidationDropSink,
} from "./validation.js";

export type {
  Component,
  Severity,
  SpanKind,
  SpanStatusCode,
  SpanContext,
  SpanEvent,
  SpanStatus,
  SpanOptions,
  Span,
  EmittedSpan,
  EmittedLog,
  TracerSink,
  Tracer,
  CreateTracerOptions,
} from "./observability.js";
export {
  createTracer,
  defaultTracerSink,
  setTracerSink,
  newTraceId,
  newSpanId,
} from "./observability.js";
