name = "codevil"
main = "src/index.ts"
compatibility_date = "2026-04-07"

[[durable_objects.bindings]]
name = "ORCHESTRATOR"
class_name = "Orchestrator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Orchestrator"]
